# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79d5d69139e8175bb582893a7b842a2871980e04a6a3f121c6d1e547986932e8acaa84fac64bbb16467bd29aaeaa2ecf57ddbe92e7ba84d97936e3fcee3e98c7

test:
  secret_key_base: c8bfbff0a5181b1c32333d766a1ee61a5864a14b642945a7658557c159dcb2f61bccb3d20b1a5aa2179bb05b3fbd236fe28c3acde703ccf7e3fb69aef5ae4af4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
